# Generated by Django 5.1.7 on 2025-03-19 22:13

import django.db.models.deletion
import modelcluster.fields
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabEquipmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('short_description', models.CharField(help_text='A brief summary of the equipment.', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the equipment.', max_digits=10)),
                ('description', wagtail.fields.RichTextField(blank=True, help_text='Detailed description of the equipment.')),
                ('main_image', models.ForeignKey(blank=True, help_text='Main image for the equipment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Lab Equipment Page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='EquipmentSpecification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('specification', models.CharField(help_text='A single specification detail.', max_length=255)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='base_site.labequipmentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
