# Generated by Django 5.1.7 on 2025-04-25 18:21

import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_site', '0001_initial'),
        ('categorized_tags', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipmentpage',
            name='categorized_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='categorized_tags.CategorizedPageTag', to='categorized_tags.CategorizedTag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='labequipmentgalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='base_site.labequipmentpage'),
        ),
        migrations.AddField(
            model_name='labequipmentaccessory',
            name='page',
            field=modelcluster.fields.ParentalManyToManyField(related_name='accessories', to='base_site.labequipmentpage'),
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='base_site.labequipmentpage'),
        ),
        migrations.AddField(
            model_name='equipmentfeature',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='base_site.labequipmentpage'),
        ),
        migrations.AddField(
            model_name='spec',
            name='spec_group',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='base_site.specgroup'),
        ),
        migrations.AddField(
            model_name='equipmentmodelspecgroup',
            name='equipment_model',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='base_site.equipmentmodel'),
        ),
        migrations.AddField(
            model_name='labequipmentpagespecgroup',
            name='LabEquipmentPage',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='base_site.labequipmentpage'),
        ),
    ]
