# Generated by Django 5.1.7 on 2025-04-25 19:10

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiproductpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text to display at the top of the page'),
        ),
        migrations.AddField(
            model_name='multiproductpage',
            name='intro_title',
            field=models.CharField(blank=True, help_text='Title to display at the top of the page', max_length=255),
        ),
    ]
