# Generated by Django 5.1.7 on 2025-03-19 22:52

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0002_labequipmentpage_equipmentspecification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labequipmentpage',
            name='short_description',
            field=wagtail.fields.RichTextField(blank=True, help_text='A brief summary of the equipment.'),
        ),
    ]
