# Generated by Django 5.1.7 on 2025-04-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0002_alter_equipmentfeature_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentspecification',
            name='spec_key',
            field=models.CharField(help_text='The key for a key-value specification (e.g. height).', max_length=255),
        ),
        migrations.AlterField(
            model_name='equipmentspecification',
            name='spec_value',
            field=models.CharField(help_text='The value for a key-value specification (e.g. 50").', max_length=255),
        ),
    ]
