# Generated by Django 5.1.7 on 2025-04-25 19:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0003_multiproductpage_intro_text_and_more'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipmentgalleryimage',
            name='is_fallback',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('hero_title', models.CharField(default='Welcome to Triad Scientific', help_text='Title for the hero section', max_length=255)),
                ('hero_subtitle', models.CharField(default='Your trusted source for high-quality lab equipment and scientific supplies', help_text='Subtitle for the hero section', max_length=255)),
                ('about_title', models.CharField(default='About Triad Scientific', help_text='Title for the about section', max_length=255)),
                ('about_content', wagtail.fields.RichTextField(default='Triad Scientific has been a leading provider of laboratory equipment for over 20 years. We offer a comprehensive range of high-quality scientific instruments, supplies, and accessories.', help_text='Content for the about section')),
                ('about_image', models.ForeignKey(blank=True, help_text='Image for the about section', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
