# Generated by Django 5.1.7 on 2025-04-10 14:14

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0003_alter_equipmentspecification_spec_key_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the specification group (e.g. dimensions, construction, electrical, etc.)', max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='labequipmentpage',
            old_name='description',
            new_name='full_description',
        ),
        migrations.RemoveField(
            model_name='labequipmentpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='labequipmentpage',
            name='price',
        ),
        migrations.CreateModel(
            name='EquipmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the model', max_length=32)),
                ('model_number', models.CharField(help_text='The identification number of the model', max_length=32)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='base_site.labequipmentpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentModelSpecGroup',
            fields=[
                ('specgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_site.specgroup')),
                ('EquipmentModel', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='base_site.equipmentmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_site.specgroup',),
        ),
        migrations.CreateModel(
            name='LabEquipmentPageSpecGroup',
            fields=[
                ('specgroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_site.specgroup')),
                ('LabEquipmentPage', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_groups', to='base_site.labequipmentpage')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_site.specgroup',),
        ),
        migrations.CreateModel(
            name='LabEquipmentAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(help_text='The identification number of the accessory', max_length=32)),
                ('name', models.CharField(help_text='The name of the accessory', max_length=32)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalManyToManyField(related_name='accessories', to='base_site.labequipmentpage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LabEquipmentGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='base_site.labequipmentpage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='What the specification is measuring (e.g. height)', max_length=32)),
                ('value', models.CharField(help_text='The value of the specification (e.g. 50in)', max_length=32)),
                ('SpecGroup', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='base_site.specgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='EquipmentSpecification',
        ),
    ]
