# Generated by Django 5.1.7 on 2025-04-28 21:55

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0004_labequipmentgalleryimage_is_fallback_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40)),
                ('equipment_page_id', models.IntegerField()),
                ('equipment_model_id', models.IntegerField(blank=True, null=True)),
                ('model_name', models.CharField(max_length=128)),
                ('model_number', models.CharField(max_length=32)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('pricing', 'Pricing Request'), ('availability', 'Availability Check'), ('customization', 'Customization Options'), ('other', 'Other')], default='pricing', max_length=20)),
                ('message', models.TextField()),
                ('session_key', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='cartpage',
            name='empty_cart_text',
            field=wagtail.fields.RichTextField(blank=True, default='Your quote cart is empty. Browse our products to add items to your quote request.', help_text='Text to display when the cart is empty'),
        ),
        migrations.AddField(
            model_name='cartpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the quote cart page'),
        ),
        migrations.AddField(
            model_name='cartpage',
            name='success_message',
            field=wagtail.fields.RichTextField(blank=True, default='Thank you for your quote request. We will get back to you as soon as possible.', help_text='Message to display after submitting a quote request'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_text',
            field=wagtail.fields.RichTextField(blank=True, help_text='Introductory text for the contact page'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='intro_title',
            field=models.CharField(default='Contact Us', help_text='Title for the contact page', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='quote_request_text',
            field=wagtail.fields.RichTextField(blank=True, default='Fill out the form below to request a quote for the items in your cart.', help_text='Text to display above quote request form'),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='quote_request_title',
            field=models.CharField(default='Request a Quote', help_text='Title for quote request section', max_length=255),
        ),
        migrations.AddField(
            model_name='contactpage',
            name='thank_you_text',
            field=wagtail.fields.RichTextField(blank=True, default='Thank you for contacting us. We will get back to you as soon as possible.', help_text='Text to display after form submission'),
        ),
    ]
