# Generated by Django 5.1.7 on 2025-05-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0005_quotecartitem_quoterequest_cartpage_empty_cart_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='model_number',
        ),
        migrations.AlterField(
            model_name='equipmentmodel',
            name='name',
            field=models.CharField(help_text='The name of the model', max_length=255),
        ),
    ]
