# Generated by Django 5.1.7 on 2025-04-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0005_alter_equipmentmodel_name_alter_spec_value'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labequipmentgalleryimage',
            name='image',
        ),
        migrations.AddField(
            model_name='labequipmentgalleryimage',
            name='external_image_url',
            field=models.URLField(blank=True, help_text='If provided, this will be used instead of an uploaded image.', verbose_name='External image URL'),
        ),
        migrations.AddField(
            model_name='labequipmentgalleryimage',
            name='internal_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='labequipmentgalleryimage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='base_site.labequipmentpage'),
        ),
    ]
