# Generated by Django 5.1.7 on 2025-04-19 15:36

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0006_remove_labequipmentgalleryimage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labequipmentgalleryimage',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='base_site.labequipmentpage'),
        ),
    ]
