# Generated by Django 5.1.7 on 2025-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0006_remove_equipmentmodel_model_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipmentpage',
            name='airscience_url',
            field=models.URLField(blank=True, help_text='Original URL from the AirScience website', null=True, verbose_name='AirScience URL'),
        ),
    ]
