# Generated by Django 5.1.7 on 2025-04-19 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0007_alter_labequipmentgalleryimage_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentmodelspecgroup',
            old_name='EquipmentModel',
            new_name='equipment_model',
        ),
        migrations.RenameField(
            model_name='spec',
            old_name='SpecGroup',
            new_name='spec_group',
        ),
    ]
