# Generated by Django 5.1.7 on 2025-05-08 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0007_labequipmentpage_airscience_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labequipmentpage',
            name='airscience_url',
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='source_url',
            field=models.URLField(blank=True, help_text='Original URL where this product information was sourced from', null=True, verbose_name='Source URL'),
        ),
    ]
