# Generated by Django 5.1.7 on 2025-05-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0008_remove_labequipmentpage_airscience_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this token', max_length=100)),
                ('token', models.CharField(editable=False, help_text='Authentication token', max_length=64, unique=True)),
                ('description', models.TextField(blank=True, help_text='Description of what this token is used for')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this token is active and can be used')),
            ],
        ),
    ]
