# Generated by Django 5.1.7 on 2025-04-19 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0008_rename_equipmentmodel_equipmentmodelspecgroup_equipment_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spec',
            name='key',
            field=models.CharField(help_text='What the specification is measuring (e.g. height)', max_length=128),
        ),
        migrations.AlterField(
            model_name='specgroup',
            name='name',
            field=models.CharField(help_text='The name of the specification group (e.g. dimensions, construction, electrical, etc.)', max_length=128),
        ),
    ]
