# Generated by Django 5.1.7 on 2025-05-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0009_apitoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentmodel',
            name='model_number',
            field=models.CharField(blank=True, default='', help_text='The model number or ID', max_length=255),
        ),
    ]
