# Generated by Django 5.1.7 on 2025-05-15 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0010_equipmentmodel_model_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='labequipmentpage',
            name='data_completeness',
            field=models.FloatField(default=1.0, help_text='Score from 0.0 to 1.0 indicating how complete the product data is'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='needs_review',
            field=models.BooleanField(default=False, help_text='Flag indicating this listing needs manual review'),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='source_type',
            field=models.CharField(choices=[('new', 'New Equipment'), ('used', 'Used Equipment'), ('refurbished', 'Refurbished Equipment'), ('unknown', 'Unknown')], default='unknown', help_text='Indicates whether this is new, used, or refurbished equipment', max_length=20),
        ),
        migrations.AddField(
            model_name='labequipmentpage',
            name='specification_confidence',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='high', help_text='Confidence level in the accuracy of the specifications', max_length=10),
        ),
    ]
