# Generated by Django 5.1.7 on 2025-05-15 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_site', '0011_labequipmentpage_data_completeness_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentmodel',
            name='model_number',
        ),
        migrations.RemoveField(
            model_name='quotecartitem',
            name='model_number',
        ),
    ]
