# Generated by Django 5.1.7 on 2025-04-25 18:21

import apps.categorized_tags.models
import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default=apps.categorized_tags.models.generate_random_color, help_text='Color for this category (HSL format)', max_length=20)),
            ],
            options={
                'verbose_name': 'Tag Category',
                'verbose_name_plural': 'Tag Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategorizedTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='slug')),
                ('category', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Categorized Tag',
                'verbose_name_plural': 'Categorized Tags',
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='CategorizedPageTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorized_tagged_items', to='wagtailcore.page')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='categorized_tags.categorizedtag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
