categorized_tag_page_selector:
  category_name: "Product Application"
  url_pattern: "https://www.airscience.com/application-category?cat={category_value}"
  product_links_selector: "h3 > a"
  required: true
  log_level: "INFO"
  tag_mapping:
    # Correct URL parameters for applications that actually exist
    "products-for-animal-research": "Animal Research"
    "cannabis-and-botanical-production": "Cannabis & Botanicals"
    "brewery": "Craft Beverages"
    "farming-and-agriculture": "Farming & Agriculture"
    "forensics": "Forensic"
    "life-science": "Life Science"
    "pharma": "Pharmaceutical" 