css_selector:
  selector: "a:contains('+ details')"
  multiple: true
  extract:
    url:
      attr_selector:
        attr_name: "href"
    product_name:
      css_selector:
        selector: "preceding::text()[1]"
        extract:
          text_selector: {}
  transform:
    # Ensure URLs are absolute
    url_join:
      field: "url"
      base_url: "http://www.triadscientific.com" 