# Generated by Django 5.1.7 on 2025-04-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorized_tags_2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytag',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='name'),
        ),
    ]
