# Generated by Django 5.1.7 on 2025-04-25 14:35

import apps.categorized_tags_2.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorized_tags_2', '0002_alter_categorytag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorytag',
            name='color',
            field=models.CharField(default=apps.categorized_tags_2.models.generate_random_color, help_text='Color for this category (HSL format)', max_length=20),
        ),
        migrations.AlterField(
            model_name='categorypagetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_items', to='categorized_tags_2.categorytag'),
        ),
    ]
