# Generated by Django 5.1.7 on 2025-04-25 14:42

import apps.categorized_tags_2.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorized_tags_2', '0003_categorytag_color_alter_categorypagetag_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(default=apps.categorized_tags_2.models.generate_random_color, help_text='Color for this category (HSL format)', max_length=20)),
            ],
            options={
                'verbose_name': 'Tag Category',
                'verbose_name_plural': 'Tag Categories',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='categorytag',
            name='color',
        ),
    ]
