# Generated by Django 5.1.7 on 2025-04-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categorized_tags_2', '0006_rename_model_classes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorizedtag',
            options={'verbose_name': 'Categorized Tag', 'verbose_name_plural': 'Categorized Tags'},
        ),
    ]
