# Generated by Django 5.1.7 on 2025-05-15 18:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchURLProcessingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Batch Name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('total_urls', models.PositiveIntegerField(default=0)),
                ('processed_urls', models.PositiveIntegerField(default=0)),
                ('successful_urls', models.PositiveIntegerField(default=0)),
                ('failed_urls', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Batch URL Processing Request',
                'verbose_name_plural': 'Batch URL Processing Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='urlprocessingrequest',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='url_requests', to='ai_processing.batchurlprocessingrequest'),
        ),
    ]
