# Generated by Django 5.1.7 on 2025-05-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0004_batchurlprocessingrequest_css_selectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlprocessingrequest',
            name='created_page_id',
            field=models.IntegerField(blank=True, help_text='ID of the page created from this request', null=True),
        ),
    ]
