# Generated by Django 5.1.7 on 2025-05-16 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0006_selectorconfiguration'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlprocessingrequest',
            name='selector_configuration',
            field=models.ForeignKey(blank=True, help_text='Selected selector configuration for HTML processing', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='url_requests', to='ai_processing.selectorconfiguration'),
        ),
    ]
